# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.UploadHashedTo('categories'))),
                ('order', models.IntegerField(default=9999)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
