# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:41
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161119_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_set', to='shop.Item'),
        ),
    ]
