# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:38
from __future__ import unicode_literals

import colorful.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20161121_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default='#ffffff', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default='#ffffff', null=True),
        ),
    ]
