# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20161121_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='composition',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
