# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20161122_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=shop.utils.UploadHashedTo('categories')),
        ),
    ]
