# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:16
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default='#000000', null=True),
        ),
    ]
