# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20161205_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group_tickets',
            field=models.BooleanField(default=True, verbose_name='Group individuals tickets in one'),
        ),
    ]
