# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models

import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.UploadHashedTo('items')),
        ),
    ]
