# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161118_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.Item'),
        ),
    ]
