# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_item_group_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group_tickets',
            field=models.BooleanField(default=False, verbose_name='Group individuals tickets in one'),
        ),
    ]
